ARG CUDA_VERSION="cu124"
ARG LLAMA_VERSION="0.2.69"
FROM docker.texttechnologylab.org/llm/llama-cpp-python/${CUDA_VERSION}/deps:${LLAMA_VERSION} as setup

ENV HOST 0.0.0.0
ENV PORT 9714
ENV SSL_KEYFILE=
ENV SSL_CERTFILE=
ENV CONFIG_FILE /app/config.json

FROM setup as component

WORKDIR /app/
COPY ./src/main/python/ /app/
COPY ./src/main/lua/communication_layer.lua /app/

CMD gunicorn wsgi:app -b ${HOST}:${PORT} -k uvicorn.workers.UvicornWorker
